services:
  database:
    container_name: dropbox-like-rust-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - database_volume:/var/lib/postgresql/data/

volumes:
  database_volume:
