services:
  database:
    container_name: dev-dropbox-like-rust-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database_volume:/var/lib/postgresql/data/

volumes:
  database_volume:
